name: Build and Deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create Build Directory
        run: mkdir build

      - name: Build binary
        run: deno compile -L debug --output=build/st main.ts

      - name: Compress binary
        run: |
          tar -czvf build/st.tar.gz -C build st
