name: Build and Deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          [
            x86_64-unknown-linux-gnu,
            x86_64-pc-windows-msvc,
            x86_64-apple-darwin,
            aarch64-apple-darwin,
          ]

    steps:
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create Build Directory
        run: mkdir build

      - name: Build binary
        run: deno compile -L debug --target=${{ matrix.target }} --output=build/st-${{ matrix.target }} main.ts

      - name: Compress binary
        run: |
          if [ "${{ matrix.target }}" = "x86_64-pc-windows-msvc" ]; then
            tar -czvf build/st-${{ matrix.target }}.tar.gz -C build st-${{ matrix.target }}.exe
          else
            tar -czvf build/st-${{ matrix.target }}.tar.gz -C build st-${{ matrix.target }}
          fi
